version: '2'

services:
   varnishcache:
     image: wodby/varnish
     restart: always
     ports:
       - "8000:6081"
     environment:
       VARNISH_BACKEND_HOST: drupalwww
   drupalwww:
     image: bms8197/drupal:drupal-9.4.1-php8.1-fpm-bullseye
     restart: always
     volumes:
       wwwroot: /home/site/wwwroot
volumes:
  wwwroot:
