version: '2'

services:
   varnishcache:
     image: wodby/varnish
     restart: always
     ports:
       - "8000:6081"
     environment:
       VARNISH_BACKEND_HOST: drupalwww
   drupalwww:
     image: compuccino/drupal-9.2:latest
     restart: always
     volumes:
       wwwroot: /home/site/wwwroot
volumes:
  wwwroot:
